### ISSUE TITLE
在typescript项目中使用react-navigation - 一寸欢喜

### ISSUE THREAD

**Issue by youngjuning** [yangjunning/youngjuning#8]
https://youngjuning.js.org/2019/react-navigation-react-native-typescript/ 

 这是杨俊宁写博客的地方，This is youngjuning's blog,

**Comment by youngjuning** [comment]
再次感谢原作者：https://medium.com/@vdelacou/add-react-navigation-to-react-native-typescript-app-d1cf855b3fe7

**Comment by vdelacou** [comment]
谢谢帮我翻译！ 我住在上海😀

**Comment by youngjuning** [comment]
@vdelacou 你是中国人还是外国友人，我住在内地。

**Comment by vdelacou** [comment]
> @youngjuning
> @vdelacou 你是中国人还是外国友人，我住在内地。
> @youngjuning 我是法国人，但在中国生活了12年

**Comment by youngjuning** [comment]
> @vdelacou
> > @youngjuning
> > @vdelacou 你是中国人还是外国友人，我住在内地。
> > @youngjuning 我是法国人，但在中国生活了12年
> 

你这篇文章确实很棒，我刚开始用typescript重构项目，获益匪浅。很高兴认识你，O(∩_∩)O~
